// <auto-generated />

using System;
using Hermes.Services.EmailSenderService.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Hermes.Services.EmailSenderService.Migrations
{
    [DbContext(typeof(HermesDbContext))]
    partial class HermesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hermes.Services.EmailSenderService.Domain.Entities.EmailOutboxItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Body")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Error")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MessageId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("SentAt")
                    .HasColumnType("datetime2");

                b.Property<int>("StatusId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("EmailOutboxItems");
            });
#pragma warning restore 612, 618
        }
    }
}