FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
EXPOSE 5031:5031
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY Hermes.API.Catalog/Hermes.API.Catalog.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY Hermes.API.Catalog/ .
RUN dotnet publish -c Release -o /app/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Hermes.API.Catalog.dll"]